config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "about", to: "static_pages#about"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "signup", to: "users#new"
    post "signup", to: "users#create"

    resources :followings, only: :index
    resources :users, only: %i(show edit create update) do
    end
    resources :categories, only: %i(index show)
    resources :comics, only: %i(index show) do
      resources :chapters, only: %i(index show)
    end
    resources :relationships, only: %i(create destroy)
    resources :comments

    namespace :admin do
      root "/admin#index"
      concern :paginatable do
        get "(page/:page)", action: :index, on: :collection, as: ""
      end

      resources :comics do
        resources :chapters, only: %i(index show new create destroy)
      end
      resources :users, concerns: :paginatable, only: %i(index destroy)
      resources :comics, only: %i(show new create)
      resources :categories
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_comics, only: :home

  def home
    @slide = @latest_update
    @tab_one = @popular.per Settings.comic.popular_per_page
    @tab_two = @updated
    @tab_three = @recommended.per Settings.comic.recommended_per_page
    @tab_four = @finished.per Settings.comic.finised_per_page
  end

  def about; end

  def category; end

  private

  def set_comics
    @latest_update = Comic.latest_update
    @popular = Comic.popular.page
    @updated = Comic.latest_update
    @recommended = Comic.newly_create.page
    @finished = Comic.finished.page
  end
end

app/views/static_pages/_banner.html.erb
<section class="banner bgwhite p-t-40 p-b-40">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
        <!-- block1 -->
        <div class="block1 hov-img-zoom pos-relative m-b-30">
          <%= image_tag "/images/720x932-1.png" %>
          <div class="block1-wrapbtn w-size2">
            <%= link_to "", class: "flex-c-m size2 m-text2 bg3 hov1 trans-0-4" do %>
              Adventure
            <% end %>
          </div>
        </div>

        <!-- block1 -->
        <div class="block1 hov-img-zoom pos-relative m-b-30">
          <%= image_tag "/images/720x660-1.jpg" %>

          <div class="block1-wrapbtn w-size2">
            <%= link_to "", class: "flex-c-m size2 m-text2 bg3 hov1 trans-0-4" do %>
              Horro
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
        <!-- block1 -->
        <div class="block1 hov-img-zoom pos-relative m-b-30">
          <%= image_tag "/images/720x660-2.jpg" %>

          <div class="block1-wrapbtn w-size2">
            <%= link_to "", class: "flex-c-m size2 m-text2 bg3 hov1 trans-0-4" do %>
              Ecchi
            <% end %>
          </div>
        </div>

        <!-- block1 -->
        <div class="block1 hov-img-zoom pos-relative m-b-30">
          <%= image_tag "/images/720x932-3.jpg" %>

          <div class="block1-wrapbtn w-size2">
            <%= link_to "", class: "flex-c-m size2 m-text2 bg3 hov1 trans-0-4" do %>
              Drama
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
        <!-- block1 -->
        <div class="block1 hov-img-zoom pos-relative m-b-30">
          <%= image_tag "/images/720x932-2.jpg" %>

          <div class="block1-wrapbtn w-size2">
            <%= link_to "", class: "flex-c-m size2 m-text2 bg3 hov1 trans-0-4" do %>
              Action
            <% end %>
          </div>
        </div>

        <!-- block2 -->
        <div class="block2 wrap-pic-w pos-relative m-b-30">
          <%= image_tag "icons/bg-01.jpg" %>

          <div class="block2-content sizefull ab-t-l flex-col-c-m">
            <% unless logged_in? %>
              <h4 class="m-text4 t-center w-size3 p-b-8">
                <span><%= t ".sign_up_now" %></span>
              </h4>

              <p class="t-center w-size4">
                <%= t ".join_now" %>
              </p>
            <% else %>
              <h4 class="m-text4 t-center w-size3 p-b-8">
                <span><%= t ".alright" %></span>
              </h4>

              <p class="t-center w-size4">
                <%= t ".alright_content" %>
              </p>
            <% end %>

            <div class="w-size2 p-t-25">
              <% unless logged_in? %>
                <%= link_to signup_path, class: "flex-c-m size2 bg4 bo-rad-23 hov1 m-text3 trans-0-4" do %>
                  <%= t ".sign_up" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_comic.html.erb
<section class="blog bgwhite p-t-94 p-b-65">
  <div class="container">
    <div class="sec-title p-b-52">
      <h3 class="m-text5 t-center">
        Trendding Comic
      </h3>
    </div>

    <div class="row">
      <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
        <!-- Block3 -->
        <div class="block3">
          <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
            <%= image_tag "/images/manga/720x539-1.jpg" %>
          </a>

          <div class="block3-txt p-t-14">
            <h4 class="p-b-7">
              <a href="blog-detail.html" class="m-text11">
                One Piece
              </a>
            </h4>

            <span class="s-text6">Author</span> <span class="s-text7">Eiichiro Oda</span>
            <span class="s-text6">on</span> <span class="s-text7">July 22, 2011</span>

            <p class="s-text8 p-t-16">
              One Piece là câu truyện kể về Luffy và các thuyền viên của mình.
              Khi còn nhỏ, Luffy ước mơ trở thành Vua Hải Tặc.
              Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su,
              nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc..
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
        <!-- Block3 -->
        <div class="block3">
          <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
            <%= image_tag "/images/manga/720x539-2.jpg" %>
          </a>

          <div class="block3-txt p-t-14">
            <h4 class="p-b-7">
              <a href="blog-detail.html" class="m-text11">
                Dragon Ball
              </a>
            </h4>

            <span class="s-text6">Author</span> <span class="s-text7">Akira Toriyama</span>
            <span class="s-text6">on</span> <span class="s-text7">July 18, 2010</span>

            <p class="s-text8 p-t-16">
              Câu truyện kể về một cậu bé tên Songoku cùng nhóm bạn của mình tham gia những chuyến phiêu lưu tìm ngọc rồng, chống lại cái ác bảo vệ trái đất.
              Nhân vật Songoku được mọi người ưa thích bởi tính thánh thiện và ngây ngô của mình.
              Câu truyện lôi cuốn người qua những tình huống phiêu lưu kì thú, những pha đấu võ đẹp mắt, và những tình huống hài hước.
              Dragon ball là bộ truyện tranh thuộc nhóm nổi tiếng nhất thế giới, được rất nhiều bạn trẻ ưa thích.
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
        <!-- Block3 -->
        <div class="block3">
          <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
            <%= image_tag "/images/manga/720x539-3.jpg" %>
          </a>

          <div class="block3-txt p-t-14">
            <h4 class="p-b-7">
              <a href="blog-detail.html" class="m-text11">
                The Seven Deadly Sins
              </a>
            </h4>

            <span class="s-text6">Author</span> <span class="s-text7">Suzuki Nakaba</span>
            <span class="s-text6">on</span> <span class="s-text7">July 2, 2017</span>

            <p class="s-text8 p-t-16">
              “Thất đại ác nhân”, một nhóm chiến binh có tham vọng lật đổ vương quốc Britannia,
              được cho là đã bị tiêu diệt bởi các “hiệp sĩ thánh chiến” mặc dù vẫn còn 1 số người cho rằng họ vẫn còn sống.
              10 năm sau, Các hiệp sĩ thánh chiến đã làm 1 cuộc đảo chính và khống chế đức vua,
              họ trở thành người cai trị độc tài mới của vương quốc. Elizabeth, con gái duy nhất của nhà vua,
              đã lên đường tìm “thất đại ác nhân” để nhờ họ tái chiếm lại vương quốc.
              Công chúa có thành công trong việc tìm kiếm “thất đại ác nhân”, các “hiệp sĩ thánh chiến” sẽ làm gì để ngăn chăn cô? xem các chap truyện sau sẽ rõ.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_comic_slide.html.erb
<section class="newproduct bgwhite p-t-45 p-b-105">
  <div class="container">
    <div class="sec-title p-b-60">
      <h3 class="m-text5"><%= t ".manga_updated" %></h3>
    </div>
    <div class="wrap-slick2">
      <div class="slick2">
        <%= @slide.each do |item| %>
          <div class="item-slick2 p-l-15 p-r-15">
            <div class="block2">
              <% case item.status %>
              <% when "newly_created" %>
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
              <% when "newly_update" %>
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelupdated">
              <% when "hot" %>
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelhot">
              <% when "finished" %>
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelfinished">
              <% else %>
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-label">
              <% end %>
              <% if item.thumb.present? %>
                <%= image_tag item.thumb.url %>
              <% else %>
                <%= image_tag "comic-default.png" %>
              <% end %>
                <div class="block2-overlay trans-0-4">
                  <% if logged_in? %>
                    <%= render "shared/links_follow", comic: item %>
                  <% else %>
                    <%= link_to login_path, class: "block2-btn-addwishlist hov-pointer trans-0-4" do %>
                      <i class="fa fa-heart"></i>
                    <% end %>
                  <% end %>
                  <div class="block2-btn-addcart w-size1 trans-0-4">
                    <%= link_to comic_path(item), class: "flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4" do %>
                      <%= t "common.read_now" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="block2-txt p-t-20">
                <%= link_to item.name, comic_path(item), class: "block2-name dis-block s-text3 p-b-5" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_our_comic.html.erb
<section class="bgwhite p-t-45 p-b-58">
  <div class="container">
    <div class="sec-title p-b-22">
      <h3 class="m-text5 t-center"><%= t ".title" %></h3>
    </div>

    <div class="tab01">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#best-seller" role="tab">
            <%= t ".popular" %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#featured" role="tab">
            <%= t ".latest_update" %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#sale" role="tab">
            <%= t ".recommended" %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#top-rate" role="tab">
            <%= t ".finished" %>
          </a>
        </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content p-t-35">
        <!-- Tab 1 -->
        <div class="tab-pane fade show active" id="best-seller" role="tabpanel">
          <div class="row">
            <%= render "shared/comic_item", object: @tab_one %>
          </div>
        </div>
        <!-- Tab 2 -->
        <div class="tab-pane fade" id="featured" role="tabpanel">
          <div class="row">
            <%= render "shared/comic_item", object: @tab_two %>
          </div>
        </div>
        <!-- Tab 3 -->
        <div class="tab-pane fade" id="sale" role="tabpanel">
          <div class="row">
            <%= render "shared/comic_item", object: @tab_three %>
          </div>
        </div>
        <!-- Tab 4  -->
        <div class="tab-pane fade" id="top-rate" role="tabpanel">
          <div class="row">
            <%= render "shared/comic_item", object: @tab_four %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>

<body class="animsition">
  <section class="bg-title-page p-t-40 p-b-50 flex-col-c-m">
    <h2 class="l-text2 t-center"><%= t ".title" %></h2>
  </section>
  <section class="bgwhite p-t-66 p-b-38">
    <div class="container">
      <div class="row">
        <div class="col-md-4 p-b-30">
          <div class="hov-img-zoom">
            <%= image_tag "/images/common/about-720x866.jpg" %>
          </div>
        </div>
        <div class="col-md-8 p-b-30">
          <h3 class="m-text26 p-t-15 p-b-16"><%= t ".our_story" %></h3>
          <p class="p-b-28"><%= t ".content" %></p>
          <div class="bo13 p-l-29 m-l-9 p-b-10">
            <p class="p-b-11"><%= t ".content_info" %></p>
            <span class="s-text7"><%= t ".author" %></span>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>

<body class="animsition">

	<%= render "banner" %>
	<%= render "comic_slide" %>
	<%= render "our_comic" %>
	<%= render "comic" %>

	<!-- Instagram -->
	<section class="instagram p-t-20">
		<div class="sec-title p-b-52 p-l-15 p-r-15">
			<h3 class="m-text5 t-center">
				@ follow us on Instagram - Feature
			</h3>
		</div>

		<div class="flex-w">
			<!-- Block4 -->
			<div class="block4 wrap-pic-w">
				<%= image_tag "/images/gallery-03.jpg" %>

				<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
					<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
						<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
						<span class="p-t-2">39</span>
					</span>

					<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
						<p class="s-text10 m-b-15 h-size1 of-hidden">
							Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
						</p>

						<span class="s-text9">
							Photo by @nancyward
						</span>
					</div>
				</a>
			</div>

			<!-- Block4 -->
			<div class="block4 wrap-pic-w">
				<%= image_tag "/images/gallery-07.jpg" %>

				<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
					<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
						<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
						<span class="p-t-2">39</span>
					</span>

					<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
						<p class="s-text10 m-b-15 h-size1 of-hidden">
							Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
						</p>

						<span class="s-text9">
							Photo by @nancyward
						</span>
					</div>
				</a>
			</div>

			<!-- Block4 -->
			<div class="block4 wrap-pic-w">
				<%= image_tag "/images/gallery-09.jpg" %>

				<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
					<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
						<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
						<span class="p-t-2">39</span>
					</span>

					<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
						<p class="s-text10 m-b-15 h-size1 of-hidden">
							Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
						</p>

						<span class="s-text9">
							Photo by @nancyward
						</span>
					</div>
				</a>
			</div>

			<!-- Block4 -->
			<div class="block4 wrap-pic-w">
				<%= image_tag "/images/gallery-13.jpg" %>

				<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
					<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
						<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
						<span class="p-t-2">39</span>
					</span>

					<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
						<p class="s-text10 m-b-15 h-size1 of-hidden">
							Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
						</p>

						<span class="s-text9">
							Photo by @nancyward
						</span>
					</div>
				</a>
			</div>

			<!-- Block4 -->
			<div class="block4 wrap-pic-w">
				<%= image_tag "/images/gallery-15.jpg" %>

				<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
					<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
						<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
						<span class="p-t-2">39</span>
					</span>

					<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
						<p class="s-text10 m-b-15 h-size1 of-hidden">
							Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
						</p>

						<span class="s-text9">
							Photo by @nancyward
						</span>
					</div>
				</a>
			</div>
		</div>
	</section>

	<!-- Shipping -->
	<section class="shipping bgwhite p-t-62 p-b-46">
		<div class="flex-w p-l-15 p-r-15">
			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Simulcasts Fresh From Japan
				</h4>

				<span class="s-text11 t-center">
					As soon as 1 hour after Japanese broadcast
				</span>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
				<h4 class="m-text12 t-center">
					Watch AD-Free in HD
				</h4>

				<span class="s-text11 t-center">
					Watch all shows ad-free in HD on all available devices
				</span>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Access All Anime & Manga
				</h4>

				<span class="s-text11 t-center">
					Enjoy our entire library of anime, manga, and drama titles
				</span>
			</div>
		</div>
	</section>
</body>

<script type="text/javascript">
  $(".selection-1").select2({
    minimumResultsForSearch: 20,
    dropdownParent: $('#dropDownSelect1')
  });
</script>