config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "about", to: "static_pages#about"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "signup", to: "users#new"
    post "signup", to: "users#create"

    resources :followings, only: :index
    resources :users, only: %i(show edit create update) do
    end
    resources :categories, only: %i(index show)
    resources :comics, only: %i(index show) do
      resources :chapters, only: %i(index show)
    end
    resources :relationships, only: %i(create destroy)
    resources :comments

    namespace :admin do
      root "/admin#index"
      concern :paginatable do
        get "(page/:page)", action: :index, on: :collection, as: ""
      end

      resources :comics do
        resources :chapters, only: %i(index show new create destroy)
      end
      resources :users, concerns: :paginatable, only: %i(index destroy)
      resources :comics, only: %i(show new create)
      resources :categories
    end
  end
end

app/views/admin/_content_header.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= yield :title %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item">
            <%= link_to t(".home"), admin_root_path %>
          </li>
          <li class="breadcrumb-item active"><%= yield :title %></li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/admin/_footer.html.erb
<footer class="main-footer">
  <strong><%= raw t ".copyright" %></strong>
  <%= t ".content" %>
  <div class="float-right d-none d-sm-inline-block">
    <%= raw t ".version" %>
  </div>
</footer>

app/views/admin/_navbar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "#", class: "nav-link", data: {widget: "pushmenu"} do %>
        <i class="fa fa-bars"></i>
      <% end %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t(".home"), admin_root_path, class: "nav-link" %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t(".user_home_pape"), root_url, class: "nav-link" %>
    </li>
  </ul>

  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </form>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item d-none d-sm-inline-block">
      <span class="topbar-email nav-link">
        <%= link_to_unless I18n.locale == :en, t("language.en"), locale: :en %> |
        <%= link_to_unless I18n.locale == :vi, t("language.vi"), locale: :vi %>
      </span>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t(".logout"), logout_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/admin/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <%= link_to admin_root_path, class: "brand-link"  do %>
    <%= image_tag "icons/AdminLTELogo.png", class: "brand-image img-circle elevation-3 custom-logo-admin" %>
    <span class="brand-text font-weight-light"><%= t ".title_page" %></span>
  <% end %>

  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= image_tag "icons/user2-160x160", class: "img-circle elevation-2" %>
      </div>
      <div class="info">
        <%= link_to current_user.name, "#", class: "d-block" %>
      </div>
    </div>

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to admin_root_path, class: "nav-link active" do %>
            <i class="nav-icon fa fa-dashboard"></i>
            <p class="admin-sidebar-text"><%= t ".dashboard" %></p>
          <% end %>
        </li>
        <li class="nav-header"><%= t ".mng_users" %></li>
        <li class="nav-item">
          <%= link_to admin_users_path, class: "nav-link" do %>
            <i class="nav-icon fa fa-users"></i>
            <p><%= t ".list_users" %></p>
          <% end %>
        </li>
        <li class="nav-header"><%= t ".mng_manga" %></li>
        <li class="nav-item">
          <%= link_to new_admin_comic_path, class: "nav-link" do %>
            <i class="nav-icon fa fa-plus-square"></i>
            <p><%= t ".new_manga" %></p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_comics_path, class: "nav-link" do %>
            <i class="nav-icon fa fa-file"></i>
            <p><%= t ".list_manga" %></p>
          <% end %>
        </li>
        <li class="nav-header"><%= t ".mng_category" %></li>
        <li class="nav-item">
          <%= link_to admin_categories_path, class: "nav-link" do %>
            <i class="nav-icon fa fa-file"></i>
            <p><%= t "admin.categories.index.list_category" %></p>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/admin/index.html.erb
<% provide :title, t(".title") %>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header border-0">
        <h3 class="card-title"><%= t ".manga" %></h3>
        <div class="card-tools">
          <%= link_to "#", class: "btn btn-tool btn-sm"  do %>
            <i class="fa fa-download"></i>
          <% end %>
          <%= link_to "#", class: "btn btn-tool btn-sm"  do %>
            <i class="fa fa-bars"></i>
          <% end %>
        </div>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped table-valign-middle">
          <thead>
          <tr>
            <th><%= t ".manga" %></th>
            <th><%= t ".chapter" %></th>
            <th><%= t ".views" %></th>
            <th><%= t ".options" %></th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= image_tag "/images/admin/default-150x150.png", class: "img-circle img-size-32 mr-2" %>
                Some Chapter
              </td>
              <td>19293</td>
              <td>
                <small class="text-success mr-1">
                  <i class="fa fa-arrow-up"></i>
                  12%
                </small>
                12,000 Sold
              </td>
              <td>
                <%= link_to "#", class: "text-muted"  do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <%= image_tag "/images/admin/default-150x150.png", class: "img-circle img-size-32 mr-2" %>
                Another Chapter
              </td>
              <td>122222</td>
              <td>
                <small class="text-warning mr-1">
                  <i class="fa fa-arrow-down"></i>
                  0.5%
                </small>
                123,234 Sold
              </td>
              <td>
                <%= link_to "#", class: "text-muted"  do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header border-0">
        <h3 class="card-title"><%= t ".over_views" %></h3>
        <div class="card-tools">
          <%= link_to "#",class: "btn btn-sm btn-tool" do %>
            <i class="fa fa-download"></i>
          <% end %>
          <%= link_to "#",class: "btn btn-sm btn-tool" do %>
            <i class="fa fa-bars"></i>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
          <p class="text-success text-xl">
            <i class="ion ion-ios-refresh-empty"></i>
          </p>
          <p class="d-flex flex-column text-right">
            <span class="font-weight-bold">
              <i class="ion ion-android-arrow-up text-success"></i> 12%
            </span>
            <span class="text-muted"><%= t ".conversion_rate" %></span>
          </p>
        </div>
        <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
          <p class="text-warning text-xl">
            <i class="ion ion-ios-cart-outline"></i>
          </p>
          <p class="d-flex flex-column text-right">
            <span class="font-weight-bold">
              <i class="ion ion-android-arrow-up text-warning"></i> 0.8%
            </span>
            <span class="text-muted"><%= t ".read_rate" %></span>
          </p>
        </div>
        <div class="d-flex justify-content-between align-items-center mb-0">
          <p class="text-danger text-xl">
            <i class="ion ion-ios-people-outline"></i>
          </p>
          <p class="d-flex flex-column text-right">
            <span class="font-weight-bold">
              <i class="ion ion-android-arrow-down text-danger"></i> 1%
            </span>
            <span class="text-muted"><%= t ".follow_rate" %></span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>