config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "about", to: "static_pages#about"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "signup", to: "users#new"
    post "signup", to: "users#create"

    resources :followings, only: :index
    resources :users, only: %i(show edit create update) do
    end
    resources :categories, only: %i(index show)
    resources :comics, only: %i(index show) do
      resources :chapters, only: %i(index show)
    end
    resources :relationships, only: %i(create destroy)
    resources :comments

    namespace :admin do
      root "/admin#index"
      concern :paginatable do
        get "(page/:page)", action: :index, on: :collection, as: ""
      end

      resources :comics do
        resources :chapters, only: %i(index show new create destroy)
      end
      resources :users, concerns: :paginatable, only: %i(index destroy)
      resources :comics, only: %i(show new create)
      resources :categories
    end
  end
end

app/models/comic.rb
class Comic < ApplicationRecord
  COMIC_ATTR = %i(name author description thumb publish_date
                  views status category_id).freeze

  has_many :relationships
  has_many :likes, through: :relationships, source: :relationshipable,
                  source_type: :Like
  has_many :following, through: :relationships,
                      source: :relationshipable,
                      source_type: :ComicFollow
  has_many :comments, dependent: :destroy
  has_many :chapters, dependent: :destroy
  belongs_to :category

  validates :name, presence: true,
                   length: {maximum: Settings.comic.name.max_length}
  validates :author, presence: true,
                     length: {maximum: Settings.comic.author.max_length}
  validates :description, presence: true,
                  length: {maximum: Settings.comic.description.max_length}
  validate :thumb_size

  mount_uploader :thumb, ThumbUploader

  scope :name_alphabet, ->{order :name}
  scope :newly_create, ->{order created_at: :desc}
  scope :popular, ->{order views: :desc}
  scope :latest_update, ->{order updated_at: :desc}
  scope :finished, ->{where status: Settings.comic.finished}
  scope :by_category, ->(id){joins(:category).merge(where(category_id: id))}

  enum status: {
    newly_created: Settings.comic.created,
    newly_update: Settings.comic.updated,
    hot: Settings.comic.hot,
    finished: Settings.comic.finished
  }

  private

  def thumb_size
    return unless thumb.size > Settings.comic.thumb_size.megabytes

    errors.add :thumb, t("mix.valid_size")
  end
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < AdminController
  before_action :load_comic, only: %i(show edit update destroy)

  def index
    @comics = Comic.newly_create.page(params[:page])
                   .per Settings.comic.per_page
  end

  def show
    @category = Category.find_by id: @comic.category_id
    @chapters = @comic.chapters.recent_upload.page(params[:page])
                      .per Settings.chapter.per_page
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new comic_params

    if @comic.save
      flash[:success] = t ".success"
      redirect_to admin_comic_path(@comic)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comic.update_attributes comic_params
      flash[:success] = t ".success"
      redirect_to admin_comics_path
    else
      flash.now[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    if @comic.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to admin_comics_path
  end
  private

  def comic_params
    params.require(:comic).permit Comic::COMIC_ATTR
  end

  def load_comic
    @comic = Comic.find_by id: params[:id]
    return if @comic

    flash[:danger] = t "common.comic_not_found"
    redirect_to admin_root_path
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :load_comic, only: :show

  def index
    @comics = Comic.name_alphabet.page(params[:page])
                   .per Settings.comic.per_page
  end

  def show
    @chapters = @comic.chapters.recent_upload.page(params[:page])
                      .per Settings.chapter.for_user_per_page
    @trendding = Comic.popular.page.per Settings.comic.trendding_right
    @categories = Category.sort_by_name
  end

  private

  def load_comic
    @comic = Comic.find_by id: params[:id]
    return if @comic

    flash[:danger] = t "common.comic_not_found"
    redirect_to root_url
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
  def get_category category_id
    return unless (@category = Category.find_by id: category_id.to_s)

    @category.name
  end
end

app/views/comics/_comic.html.erb
<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
  <div class="block2">
    <% case comic.status %>
    <% when "newly_created" %>
      <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
    <% when "newly_update" %>
      <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelupdated">
    <% when "hot" %>
      <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelhot">
    <% when "finished" %>
      <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelfinished">
    <% else %>
      <div class="block2-img wrap-pic-w of-hidden pos-relative block2-label">
    <% end %>
    <% if comic.thumb.present? %>
      <%= image_tag comic.thumb.url %>
    <% else %>
      <%= image_tag "/images/comic/not-found.png" %>
    <% end %>
      <div class="block2-overlay trans-0-4">
        <% if logged_in? %>
          <%= render "shared/links_follow", comic: comic %>
        <% else %>
          <%= link_to login_path, class: "block2-btn-addwishlist hov-pointer trans-0-4" do %>
            <i class="fa fa-heart-o"></i>
          <% end %>
        <% end %>
        <div class="block2-btn-addcart w-size1 trans-0-4">
          <%= link_to comic_path(comic), class: "flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4"  do %>
            <%= t ".read" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="block2-txt p-t-20">
      <%= link_to comic.name, comic_path(comic), class: "block2-name dis-block s-text3 p-b-5" %>
    </div>
  </div>
</div>

app/views/comics/_follow.html.erb
<%= form_for current_user.relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :comic_id, @comic.id %></div>
  <div><%= hidden_field_tag :follow, Settings.follow %></div>
  <li class="li02">
    <span class="btn-follow-parent">
      <i class="fa fa-heart-o"></i>&nbsp;
      <%= f.submit t(".follow"), class: "btn-follow" %>
    </span>
  </li>
<% end %>

app/views/comics/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following? @comic %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
</div>

app/views/comics/_like.html.erb
<%= form_for current_user.relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :comic_id, @comic.id %></div>
  <div><%= hidden_field_tag :like, Settings.like %></div>
  <li class="li03">
    <span class="btn-like-parent">
      <i class="fa fa-thumbs-o-up"></i>&nbsp;
      <%= f.submit t(".like"), class: "btn-like" %>
    </span>
  </li>
<% end %>

app/views/comics/_like_form.html.erb
<div id="like_form">
  <% if current_user.liked? @comic %>
    <%= render "unlike" %>
  <% else %>
    <%= render "like" %>
  <% end %>
</div>

app/views/comics/_unfollow.html.erb
<%= form_for current_user.relationships.find_by(comic_id: @comic.id),
             html: { method: :delete }, remote: true  do |f| %>
  <div><%= hidden_field_tag :follow, Settings.follow %></div>
  <li class="li02">
    <span class="btn-follow-parent">
      <i class="fa fa-heart"></i>&nbsp;
      <%= f.submit t(".unfollow"), class: "btn-follow" %>
    </span>
  </li>
<% end %>

app/views/comics/_unlike.html.erb
<%= form_for current_user.relationships.find_by(comic_id: @comic.id),
             html: { method: :delete }, remote: true  do |f| %>
  <div><%= hidden_field_tag :like, Settings.like %></div>
  <li class="li03">
    <span class="btn-like-parent">
      <i class="fa fa-thumbs-up"></i>&nbsp;
      <%= f.submit t(".unlike"), class: "btn-like" %>
    </span>
  </li>
<% end %>

app/views/comics/show.html.erb
<% provide :title, @comic.name %>

<section class="bgwhite p-t-60">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-lg-9 p-b-75">
        <div class="p-r-50 p-r-0-lg">
          <div class="item-blog p-b-10">
            <div id="item-detail">
              <h1 class="title-detail">
                <%= @comic.name %>
              </h1>
              <% if @comic.chapters.present? %>
                <time class="small">
                  [
                    <%= t ".updated_at" %>:
                    <%= distance_of_time_in_words(Time.now,
                          @comic.chapters.last.updated_at) %>
                    <%= t ".ago" %>
                  ]
                </time>
              <% end %>
              <div class="detail-info">
                <div class="row">
                  <div class="col-md-5 col-xs-5 col-image">
                    <%= link_to "", class: "item-blog-img pos-relative dis-block hov-img-zoom" do %>
                      <% if @comic.thumb.present? %>
                        <%= image_tag @comic.thumb.url %>
                      <% else %>
                        <%= image_tag "comic-default.png" %>
                      <% end %>
                      <% if @comic.publish_date.present? %>
                        <span class="item-blog-date dis-block flex-c-m pos1 size17 bg4 s-text1">
                          <%= @comic.publish_date %>
                        </span>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="col-md-7 col-xs-7 col-info">
                    <ul class="list-info">
                      <li class="author row">
                        <p class="name col-md-4 col-xs-4 text-custom-detail">
                          <i class="fa fa-user"></i>&nbsp;<%= t ".author" %>
                        </p>
                        <p class="col-md-8 col-xs-8">
                          <%= link_to @comic.author, "#" %>
                        </p>
                      </li>
                      <li class="status row">
                        <p class="name col-md-4 col-xs-4 text-custom-detail">
                          <i class="fa fa-rss"></i>&nbsp;<%= t ".status" %>
                        </p>
                        <% if "finished" == @comic.status %>
                          <p class="col-md-8 col-xs-8 text-danger">
                            <%= t ".finished" %>
                          </p>
                        <% else %>
                          <p class="col-md-8 col-xs-8 text-warning">
                            <%= t ".continue" %>
                          </p>
                        <% end %>
                      </li>
                      <li class="status row">
                        <p class="name col-md-4 col-xs-4 text-custom-detail">
                          <i class="fa fa-tags"></i>&nbsp;<%= t ".statistic" %>
                        </p>
                        <p class="col-md-8 col-xs-8">
                          <span class="sp01">
                            <i class="fa fa-thumbs-up"></i>
                          </span>
                          <span class="sp02 number-like" id="liked">
                            <%= @comic.likes.size %>&emsp;
                          </span>
                          <span class="sp01">
                            <i class="fa fa-heart"></i>
                          </span>
                          <span class="sp02" id="followed">
                            <%= @comic.following.size %>&emsp;
                          </span>
                          <span class="sp01">
                            <i class="fa fa fa-eye"></i>
                          </span>
                          <span class="sp02">
                            <%= @comic.views %>&emsp;
                          </span>
                        </p>
                      </li>
                      <li class="kind row m-t-20">
                        <p class="name col-md-12 col-xs-12 text-custom-detail">
                          <%= link_to category_path(@comic.category),
                            class: "btn btn-sm btn-outline-secondary" do %>
                            <%= @comic.category.name %>
                          <% end %>
                        </p>
                      </li>
                    </ul>
                    <div class="read-action mrt10 liparent row">
                      <div class="col-md-6">
                        <li class="li01">
                          <% if @comic.chapters.size > 1 %>
                            <%= link_to comic_chapter_path(@comic,
                                          @comic.chapters.first) do %>
                              <i class="fa fa-book"></i>&nbsp;
                              <%= t ".first_read" %>
                            <% end %>
                          <% end %>
                        </li>
                        <% if logged_in? %>
                          <%= render "follow_form", comic: @comic %>
                        <% else %>
                          <li class="li02">
                            <%= link_to login_path, class: "pd-l-0" do %>
                              <span class="btn-follow-parent">
                                <i class="fa fa-heart-o"></i>&nbsp;
                                <%= t ".follow" %>
                              </span>
                            <% end %>
                          </li>
                        <% end %>
                      </div>
                      <div class="col-md-6">
                        <li class="li04">
                          <% if @comic.chapters.size > 2 %>
                            <%= link_to comic_chapter_path(@comic,
                                          @comic.chapters.last) do %>
                              <i class="fa fa-paper-plane"></i>&nbsp;
                              <%= t ".last_read" %>
                            <% end %>
                          <% end %>
                        </li>
                        <% if logged_in? %>
                          <%= render "like_form", comic: @comic %>
                        <% else %>
                          <li class="li03">
                            <%= link_to login_path, class: "pd-l-0" do %>
                              <span class="btn-follow-parent">
                                <i class="fa fa-thumbs-o-up"></i>&nbsp;
                                <%= t ".like" %>
                              </span>
                            <% end %>
                          </li>
                        <% end %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="detail-content">
                        <h3 class="list-title">
                          <i class="fa fa-file-text-o"></i>&nbsp;
                          <%= t ".content" %>
                        </h3>
                        <p><%= @comic.description %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="item-blog p-b-20">
            <div class="item-blog-txt p-t-33 block02">
              <div class="title p-b-11">
                  <h2 class="story-detail-title m-text24">
                    <%= t ".list_chapter" %>
                  </h2>
              </div>
              <div class="s-text8 flex-w flex-m p-b-21">
                <span>
                  <%= t ".by_admin" %><span class="m-l-3 m-r-6">|</span>
                </span>
                <span>
                  <%= @comic.category.name %><span class="m-l-3 m-r-6">|</span>
                </span>
                <span>8 <%= t ".comment" %></span>
              </div>
              <% if @comic.chapters.any? %>
                <div class="box">
                  <div class="works-chapter-list">
                    <%= render @chapters %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12 col-md-1"></div>
                  <div class="col-sm-12 col-md-11">
                    <div class="custom_paginate float-right">
                      <%= paginate @chapters, theme: "twitter-bootstrap-4" %>
                    </div>
                  </div>
                </div>
              <% else %>
                <div class="box">
                  <div class="works-chapter-list">
                    <h4><%= t ".empty" %></h4>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-3 col-lg-3 p-b-75">
        <div class="rightbar">
          <h4 class="m-text23 p-t-65 p-b-34">
            <%=  t ".trendding_title" %>
          </h4>
          <ul class="bgwhite">
            <% @trendding.each do |item| %>
              <li class="flex-w p-b-20">
                <%= link_to comic_path(item), class: "dis-block wrap-pic-w
                              w-size22 m-r-20 trans-0-4 hov4" do %>
                  <% if item.thumb.present? %>
                    <%= image_tag item.thumb.url, class: "trendding_thumb" %>
                  <% else %>
                    <%= image_tag "comic-default.png", class: "trendding_thumb" %>
                  <% end %>
                <% end %>
                <div class="w-size23 p-t-5">
                  <%= link_to comic_path(item), class: "s-text20" do %>
                    <%= item.name %>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
          <h4 class="m-text23 p-t-50 p-b-25">
            <%= t ".tags" %>
          </h4>
          <div class="wrap-tags flex-w">
            <% @categories.each do |tag| %>
              <%= link_to "#{tag.name}-(#{tag.comics.size})",
                    category_path(tag), class: "tag-item" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>