config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "about", to: "static_pages#about"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "signup", to: "users#new"
    post "signup", to: "users#create"

    resources :followings, only: :index
    resources :users, only: %i(show edit create update) do
    end
    resources :categories, only: %i(index show)
    resources :comics, only: %i(index show) do
      resources :chapters, only: %i(index show)
    end
    resources :relationships, only: %i(create destroy)
    resources :comments

    namespace :admin do
      root "/admin#index"
      concern :paginatable do
        get "(page/:page)", action: :index, on: :collection, as: ""
      end

      resources :comics do
        resources :chapters, only: %i(index show new create destroy)
      end
      resources :users, concerns: :paginatable, only: %i(index destroy)
      resources :comics, only: %i(show new create)
      resources :categories
    end
  end
end

app/views/shared/_comic_item.html.erb
<% object.each do |item| %>
  <div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
    <div class="block2">
      <% case item.status %>
      <% when "newly_created" %>
        <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
      <% when "newly_update" %>
        <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelupdated">
      <% when "hot" %>
        <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelhot">
      <% when "finished" %>
        <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelfinished">
      <% else %>
        <div class="block2-img wrap-pic-w of-hidden pos-relative block2-label">
      <% end %>
      <% if item.thumb.present? %>
        <%= image_tag item.thumb.url %>
      <% else %>
        <%= image_tag "comic-default.png" %>
      <% end %>
        <div class="block2-overlay trans-0-4">
          <% if logged_in? %>
            <%= render "shared/links_follow", comic: item %>
          <% else %>
            <%= link_to login_path, class: "block2-btn-addwishlist hov-pointer trans-0-4" do %>
              <i class="fa fa-heart"></i>
            <% end %>
          <% end %>
          <div class="block2-btn-addcart w-size1 trans-0-4">
            <%= link_to comic_path(item), class: "flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4" do %>
              <%= t "common.read_now" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="block2-txt p-t-20">
        <%= link_to item.name, comic_path(item), class: "block2-name dis-block s-text3 p-b-5" %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       <%= t ".form" %>
       <%= t(".error", :count => object.errors.count ) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= link_to relationships_path( init_follow, comic_id: comic.id,
    follow: Settings.follow), method: :post, remote: true,
    class: "block2-btn-addwishlist hov-pointer trans-0-4" do %>
  <i class="fa fa-heart-o icon_heart" title="<%= t ".follow" %>"></i>
<% end %>

app/views/shared/_links_follow.html.erb
<div class="link_form" id="<%= comic.id %>">
  <% if current_user.following? comic %>
    <%= render "shared/unfollow", comic: comic %>
  <% else %>
    <%= render "shared/follow", comic: comic %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <%= link_to following_user_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    <% t ".following" %>
  <% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= link_to relationship_path(load_comic_following(comic),
  follow: Settings.follow), method: :delete, remote: true,
  class: "block2-btn-addwishlist hov-pointer trans-0-4" do %>
  <i class="fa fa-heart icon_heart" title="<%= t ".unfollow" %>" ></i>
<% end %>